eslint objective
flaviostutz/onboarding-serverless-users pull request #9
Opened 2022-09-06 13:34 UTC by nielsmijnster

2022-09-07 04:05 UTC, flaviostutz requested changes
Please check comments. There are some new files that were pushed to the source Repo after you forked the project that must be used :)

2022-09-07 04:05 UTC, flaviostutz commented on .eslintrc
> +{
This file should be gotten from the folder basic-configs/. This folder was added to the the source main branch after you forked this project, so you need to pull the contents of the source folder to update your Repo with the latest files. If you look at UI of GitHub it says that your Repo is 1 commit behind the forked repo. After pulling it, move the lint config file to the root and fix the check issues. You can use the automatic fix, but I prefer to fix it file by file using the VSCode plugin so I can see the changes and understand better whats the style being enforced. Install the plugin and configure a keyboard shortcut for executing the fix on current file.

2022-09-07 04:05 UTC, flaviostutz commented on src/cow-slug.ts
> +        import { generateSlug } from 'random-word-slugs';
This seems like a identation issue

2022-09-07 04:05 UTC, flaviostutz commented on .editorconfig
> -indent_size = 2
For now we shouldn’t have this file as all formatting rules will come from eslint and this can clash with the other configuration. It’s always to keep things simple and understand why each file is in the repo.

2022-09-07 04:05 UTC, flaviostutz commented on .eslintignore
> -build/
Why are you commiting the dist folder?

2022-09-07 04:05 UTC, flaviostutz commented on .eslintrc
> +  "root": true,
This file should be gotten from folder “basic-configs”

2022-09-07 04:05 UTC, flaviostutz commented on tsconfig.json
>      "unit.test/**/*.ts"
Why are you adding folder “unit.test” if you never use it?

2022-09-07 04:05 UTC, flaviostutz commented on tsconfig.json
> +    "src/slug.ts",
Why are you adding explicitly this file if there is a wildcard rule adding all .ts files already?

Use the tsconfig file from basic-config

2022-09-07 04:05 UTC, flaviostutz commented on test/slug.test.ts
> +import { generateRandomSlugs } from "../src/slug";
Keep the tests inside the src/ folder using the same naming convention. It makes it cleaner to configure the project and keeps the test files nearer the tested files. Keep the test and the tested file in the same folder

2022-09-07 13:57 UTC, nielsmijnster commented on .eslintrc
> +{
I didn't understand it was meant to be that I had to pull this config files. But now I tried to pull it but I got an error so I copied everything in the project. I understand what you explain here to me, therefore I installed the plug-in and made a shortcut, which works very easily on every file indeed. This is a nice way of checking the code. The rest of the comments I took into account but I do not replay on everything separately, I will send you the PR with the improved setup of the project.

2022-09-07 14:01 UTC, nielsmijnster commented on .eslintrc
> +{
* send you the link of the new commit I mean ofcourse. Besides this I tried to put the tsconfig.json in the basic-project-configs folder but I got errors and could not fix it. And I added outDir and scripts so everything stayed working.

2022-09-07 21:05 UTC, flaviostutz requested changes
Filé .DSStore shouldn't be committed to the Repo. Please delete it.

2022-09-07 21:05 UTC, flaviostutz commented
The rest is on now! 🤩

2022-09-08 07:09 UTC, nielsmijnster commented
removed DSSTORE now, somehow i made 4 commits because I wanted to change the gitignore file also but I made some mistakes or it did not work, for now only deleting the DSSTORE in this commit https://github.com/flaviostutz/onboarding-serverless-users/pull/9/commits/4f346646b3419054f5a854ac74bf4c64095728aa

2022-09-26 15:43 UTC, flaviostutz requested changes
The .DS_Store file is still committed and should be added to .gitignore

2022-09-26 15:43 UTC, flaviostutz commented on .gitignore
> -DS_Store
You should add .DS_Store to gitignore too. And somehow I think it's still committed to the branch.

2022-09-27 08:27 UTC, flaviostutz approved these changes

2022-10-04 13:56 UTC, merged